# Generated by Django 5.2.7 on 2026-01-05 16:22

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accesare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_client", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pagina",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Accesări",
            },
        ),
        migrations.CreateModel(
            name="Antichitate",
            fields=[
                ("id_antichitate", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tip_obiect",
                    models.CharField(
                        choices=[
                            ("vaza", "Vază"),
                            ("tablou", "Tablou"),
                            ("obiect_muzeal", "Obiect muzeal"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("prenume", models.CharField(blank=True, max_length=100, null=True)),
                ("data_nastere", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100, unique=True)),
                ("descriere", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True)),
                (
                    "culoare_hex",
                    models.CharField(
                        default="#AAAAAA",
                        help_text="Cod HEX al culorii (ex: #FF0000)",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Editura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume_editura", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                ("id_oferta", models.AutoField(primary_key=True, serialize=False)),
                ("titlu", models.CharField(max_length=100)),
                ("procent_reducere", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("data_nasterii", models.DateField(blank=True, null=True)),
                (
                    "telefon",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "Introduceți un număr de telefon valid (10 cifre).",
                            )
                        ],
                    ),
                ),
                ("oras", models.CharField(max_length=100)),
                (
                    "tip_abonament",
                    models.CharField(
                        choices=[("basic", "Basic"), ("premium", "Premium")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Carte",
            fields=[
                ("ISBN", models.BigIntegerField(primary_key=True, serialize=False)),
                ("titlu", models.CharField(max_length=100)),
                ("an_publicatie", models.IntegerField(blank=True, null=True)),
                (
                    "pret",
                    models.DecimalField(decimal_places=2, default=10, max_digits=20),
                ),
                (
                    "imagine",
                    models.ImageField(blank=True, null=True, upload_to="documente/"),
                ),
                (
                    "autor",
                    models.ManyToManyField(
                        related_name="carti", to="aplicatie_exemplu.autor"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carti_din_categorie",
                        to="aplicatie_exemplu.categorie",
                    ),
                ),
                (
                    "id_editura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carti",
                        to="aplicatie_exemplu.editura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopieCarte",
            fields=[
                ("id_copie", models.AutoField(primary_key=True, serialize=False)),
                ("semnat_de_autor", models.BooleanField(default=False)),
                ("observatii", models.CharField(blank=True, max_length=300, null=True)),
                ("limba", models.CharField(default="Romana", max_length=100)),
                (
                    "isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copii",
                        to="aplicatie_exemplu.carte",
                    ),
                ),
                (
                    "id_oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aplicatie_exemplu.oferta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comanda",
            fields=[
                ("id_comanda", models.AutoField(primary_key=True, serialize=False)),
                ("pret", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tip_tranzactie", models.CharField(max_length=50)),
                ("data_tranzactie", models.DateTimeField(auto_now_add=True)),
                ("adresa", models.CharField(max_length=200)),
                (
                    "id_antichitate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comenzi",
                        to="aplicatie_exemplu.antichitate",
                    ),
                ),
                (
                    "id_copie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comenzi",
                        to="aplicatie_exemplu.copiecarte",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="antichitate",
            name="id_oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aplicatie_exemplu.oferta",
            ),
        ),
        migrations.CreateModel(
            name="Utilizator",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("CNP", models.CharField(max_length=13, unique=True)),
                ("nume", models.CharField(max_length=50)),
                ("prenume", models.CharField(max_length=50)),
                ("parola", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nr_telefon", models.CharField(max_length=15)),
                ("tara", models.CharField(max_length=50)),
                ("judet", models.CharField(max_length=50)),
                ("comuna", models.CharField(blank=True, max_length=50, null=True)),
                ("strada", models.CharField(max_length=100)),
                ("nr_adresa", models.CharField(max_length=10)),
                (
                    "id_comanda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilizatori",
                        to="aplicatie_exemplu.comanda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comanda",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comenzi",
                to="aplicatie_exemplu.utilizator",
            ),
        ),
        migrations.CreateModel(
            name="Abonament",
            fields=[
                ("id_abonament", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tip_abonament",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("Premium", "Premium"),
                            ("Angajat", "Angajat"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_incepere", models.DateField(default=datetime.date.today)),
                ("data_expirare", models.DateField(blank=True, null=True)),
                ("procent_reducere", models.PositiveIntegerField()),
                (
                    "id_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abonamente",
                        to="aplicatie_exemplu.utilizator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                ("id_voucher", models.AutoField(primary_key=True, serialize=False)),
                ("suma", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_incepere", models.DateField(default=datetime.date.today)),
                ("data_expirare", models.DateField(blank=True, null=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchere",
                        to="aplicatie_exemplu.utilizator",
                    ),
                ),
            ],
        ),
    ]
