# Generated by Django 5.2.7 on 2026-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicatie_exemplu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_confirmat",
            field=models.BooleanField(default=False),
        ),
    ]
