# Generated by Django 5.2.7 on 2026-01-06 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicatie_exemplu", "0002_customuser_cod_customuser_email_confirmat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vizualizare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_vizualizarii", models.DateTimeField(auto_now_add=True)),
                (
                    "produs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicatie_exemplu.carte",
                    ),
                ),
                (
                    "utilizator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
