# Generated by Django 5.2.7 on 2026-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicatie_exemplu", "0003_vizualizare"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=100)),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
                ("data_expirare", models.DateTimeField()),
                ("procent_reducere", models.IntegerField()),
                ("cod_voucher", models.CharField(max_length=20)),
                ("categorii", models.ManyToManyField(to="aplicatie_exemplu.categorie")),
            ],
        ),
    ]
