# Generated by Django 5.2.7 on 2026-01-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplicatie_exemplu", "0004_promotie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotie",
            options={
                "permissions": [
                    ("vizualizeaza_oferta", "Poate vedea oferta specială de 50%")
                ]
            },
        ),
    ]
