# Generated by Django 5.2.7 on 2026-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicatie_exemplu", "0005_alter_promotie_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("poate_bloca_utilizator", "Poate bloca sau debloca utilizatori")
                ]
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="blocat",
            field=models.BooleanField(default=False),
        ),
    ]
